version: "3"
services:
  employee-jdbc:
    image: Enrollee-service
    ports:
      - "8080:8080"
    networks:
      - enroll-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - enroll-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root  

networks:
  employee-mysql: